### ISSUE TITLE
getType should use resource name instead of eloquent model name

### ISSUE THREAD

**Issue by tomasvanrijsse** [Intermax-Cloudsourcing/laravel-open-api#2]

**Comment by patrickhoogkamer** [comment]
How would you want to handle different Resource naming conventions? For example, you could use `Resources\User` or `Resources\UserResource`.

**Comment by patrickhoogkamer** [comment]
Wrong project, this is meant for laravel-json-api. I'd say the current method is also fine over there. It's easy to configure with a `getType` method implementation as well.
