### ISSUE TITLE
Why doesn't the POST & PATH request use the Resource to generate docs?

### ISSUE THREAD

**Issue by hansgoed** [Intermax-Cloudsourcing/laravel-open-api#22]
JSON:API requires a resource to be given when creating or updating. Am I missing something in thinking that this should exactly match a Resource used to generate a response?

**Comment by patrickhoogkamer** [comment]
They don't have be exactly the same.  It's interesting to explore, but it might limit the ability to have 'read only' or 'write only' properties.

**Comment by patrickhoogkamer** [comment]
Maybe something for the laravel json api package.
